### ISSUE TITLE
Generate guessing the type of file

### ISSUE THREAD

**Issue by xescugc** [cycloidio/inframap#101]
Instead of having the `--tfstate` and `--hcl` would be good to directly use one or the other based on the file.

If used like `inframap generate hcl.tf` it's easy as we know the file extension, the hard part is if it's piped like `cat hcl.tf | inframap generate`, in this case the best guess is to try to marshal it with JSON and if it's invalid then try with HCL and return error if also invalid.

This would improve a lot the user experience as it would remove the need of `--tfstate` and `--hcl` making it much simpler and intuitive to use.

**Comment by xlr-8** [comment]
In case of doubt, the type could also be asked

**Comment by xescugc** [comment]
> In case of doubt, the type could also be asked

Yes but then it would break any piping potentially, so I think I prefer to `fail`.

What we could do is keep the `--tfstate` and `--hcl` instead of removing as my initial idea, but IDK in which case we'll not detect, the only one I can think of is invalid JSON as we'll fallback to HCL after. But it would already be invalid, and HCL would not be confused by JSON ... except if someone writes HCL in JSON which is valid IIRC but IDK how many people have that specific usecase haha.

**Comment by xescugc** [comment]
Done on https://github.com/cycloidio/inframap/pull/116
