### ISSUE TITLE
Runtime Error when Generating

### ISSUE THREAD

**Issue by SebastianAtWork** [cycloidio/inframap#120]
Hi,
really cool tool, i just have problems getting it to work on my Terraform state. It has the Azurerm provider. I am on Windows 10. When trying to inframap generate, i get the following error:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x988d24]

goroutine 1 [running]:
github.com/cycloidio/inframap/printer/dot.Dot.Print(0x0, 0x1, 0x1130740, 0xc000006018, 0xc000124620, 0x1029f70)
        /tmp/build/6b18b934/code/printer/dot/printer.go:35 +0x2c4
github.com/cycloidio/inframap/cmd.glob..func1(0x1699ea0, 0xc000056ee0, 0x1, 0x1, 0x0, 0x0)
        /tmp/build/6b18b934/code/cmd/generate.go:84 +0x12c
github.com/spf13/cobra.(*Command).execute(0x1699ea0, 0xc000056d10, 0x1, 0x1, 0x1699ea0, 0xc000056d10)
        /tmp/build/6b18b934/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x45a
github.com/spf13/cobra.(*Command).ExecuteC(0x169a3a0, 0x0, 0xa0eb80, 0xc000024178)
        /tmp/build/6b18b934/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /tmp/build/6b18b934/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cycloidio/inframap/cmd.Execute(...)
        /tmp/build/6b18b934/code/cmd/root.go:27
main.main()
        /tmp/build/6b18b934/code/main.go:10 +0x35
If you need anything else, let me know.

**Comment by xescugc** [comment]
Hi @SebastianAtWork !

Ok few things:

* Could you check you are on latest version with `inframap version` which as of now is `0.6.1`.
* Could you provide me the command you are running?
* And this last one is optional for you, we have an `inframap prune your-state-file.json` that will print a "new" State with just the information we need so it can be shared (without leaking information), you can add the `--canonicals` flag which will also replace all your resources names for random values so it's more "ofuscated". If you think this generated file is secure enough for you to share would be really good as I would be able to run the same command with the same input so I can try to reproduce it :). But this is totally optional and up to you to share.

**Comment by SebastianAtWork** [comment]
Hi, I am on 0.6.1. The prune command actually gave me another hint at what could be wrong. I generated the state file by doing a terraform state pull > state.tfstate and inframap prune state.tfstate --canonicals --tfstate gives me 2 errors:
- Unsupported state file format: The state file could not be parsed as JSON: syntax error at byte offset 1.
- Unsupported state file format: The state file does not have a "version" attribute, which is required to identify the format version.
Here is the beginning of my state file: 
{
  "version": 4,
  "terraform_version": "0.14.7",
  "serial": 46,
  "lineage": "ebffe4cc-f26f-17e7-55d2-15e084302669",
  "outputs": {},
  "resources": [
    {
I can try upgrading it to 0.14.8 again, but it gave the same runtime error.
The original command i was using for the runtime error was  :  inframap generate state.tfstate

**Comment by SebastianAtWork** [comment]
If i unset the backend, Terraform downloads the state into the folder. That state seems to work better (It gives me an empty strict digraph G {

}). So apparently theres a small difference between the actual state and the state i get with terraform state pull

**Comment by xescugc** [comment]
It's quite a mystery ... I'm trying to figure out why you get the nil pointer and I'm totally clueless.

Few things I had in mind to test:
* You are on Windows 10, I'll try to set it up just in case to see if there is anything weird with the lib.
* `Unsupported state file format: The state file could not be parsed as JSON: syntax error at byte offset 1.` This means the JSON from `terraform state pull` is wrongly formatted, I don't know how haha.
* `Unsupported state file format: The state file does not have a "version" attribute, which is required to identify the format version.` Tested the `inframap prune` just in case we where unseting the verison but we do not, so it means it's not on the `terraform state pull` which is weird also

Some solutions for you to try:
* Try to use the Docker image to see if you see anything else.
* Try to use the flags `--raw --clean=false` which will just read the State without doing any logic to make it preaty so it'll be more bulky if anything is returned.

For Azure we support connections using `azurerm_virtual_network_peering` as is what we identified for now, if you think there are other types of connections we can investigate the solutions as we are not expers on Azure hehe.

**Comment by luisdavim** [comment]
I have a similar issue:
```
cat *.tf | inframap generate --hcl
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1545e2f]

goroutine 1 [running]:
github.com/cycloidio/inframap/printer/dot.Dot.Print(0x0, 0x1, 0x1d0d920, 0xc000134008, 0x8, 0x0)
        github.com/cycloidio/inframap/printer/dot/printer.go:35 +0x2cf
github.com/cycloidio/inframap/cmd.glob..func1(0x2198760, 0xc00094ee00, 0x0, 0x1, 0x0, 0x0)
        github.com/cycloidio/inframap/cmd/generate.go:84 +0x128
github.com/spf13/cobra.(*Command).execute(0x2198760, 0xc00094edf0, 0x1, 0x1, 0x2198760, 0xc00094edf0)
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x2198c60, 0x0, 0xffffffff, 0xc00010e058)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cycloidio/inframap/cmd.Execute(...)
        github.com/cycloidio/inframap/cmd/root.go:27
main.main()
        github.com/cycloidio/inframap/main.go:10 +0x2e
```

```
cat *.tf | inframap generate --hcl --raw
strict digraph G {
        "aws_route_table_association.private"->"aws_subnet.private";
        "aws_route_table_association.private"->"aws_route_table.private";
        "aws_ecs_task_definition.app"->"aws_iam_role.ecs_task_execution_role";
        "aws_security_group.lb"->"aws_vpc.main";
        "aws_iam_role_policy_attachment.ecs_task_execution_role"->"aws_iam_role.ecs_task_execution_role";
        "aws_appautoscaling_policy.down"->"aws_ecs_cluster.main";
        "aws_appautoscaling_policy.down"->"aws_ecs_service.main";
        "aws_appautoscaling_policy.down"->"aws_appautoscaling_target.target";
        "aws_iam_role_policy_attachment.ecs_dynamodb_policy"->"aws_iam_role.ecs_task_execution_role";
        "aws_iam_role_policy_attachment.ecs_dynamodb_policy"->"aws_iam_policy.dynamodb";
        "aws_internet_gateway.gw"->"aws_vpc.main";
        "aws_subnet.private"->"aws_vpc.main";
        "aws_route.internet_access"->"aws_vpc.main";
        "aws_route.internet_access"->"aws_internet_gateway.gw";
        "aws_security_group.ecs_tasks"->"aws_security_group.lb";
        "aws_security_group.ecs_tasks"->"aws_vpc.main";
        "aws_cloudwatch_metric_alarm.service_cpu_low"->"aws_appautoscaling_policy.down";
        "aws_cloudwatch_metric_alarm.service_cpu_low"->"aws_ecs_cluster.main";
        "aws_cloudwatch_metric_alarm.service_cpu_low"->"aws_ecs_service.main";
        "aws_alb_target_group.app"->"aws_vpc.main";
        "aws_alb_listener.front_end"->"aws_alb.main";
        "aws_alb_listener.front_end"->"aws_alb_target_group.app";
        "aws_route_table.private"->"aws_vpc.main";
        "aws_route_table.private"->"aws_nat_gateway.gw";
        "aws_nat_gateway.gw"->"aws_eip.gw";
        "aws_nat_gateway.gw"->"aws_subnet.public";
        "aws_ecr_lifecycle_policy.main"->"aws_ecr_repository.main";
        "aws_appautoscaling_policy.up"->"aws_ecs_cluster.main";
        "aws_appautoscaling_policy.up"->"aws_ecs_service.main";
        "aws_appautoscaling_policy.up"->"aws_appautoscaling_target.target";
        "aws_subnet.public"->"aws_vpc.main";
        "aws_ecs_service.main"->"aws_alb_target_group.app";
        "aws_ecs_service.main"->"aws_alb_listener.front_end";
        "aws_ecs_service.main"->"aws_iam_role_policy_attachment.ecs_task_execution_role";
        "aws_ecs_service.main"->"aws_ecs_cluster.main";
        "aws_ecs_service.main"->"aws_ecs_task_definition.app";
        "aws_ecs_service.main"->"aws_security_group.ecs_tasks";
        "aws_ecs_service.main"->"aws_subnet.private";
        "aws_cloudwatch_log_stream.log_stream"->"aws_cloudwatch_log_group.log_group";
        "aws_eip.gw"->"aws_internet_gateway.gw";
        "aws_alb.main"->"aws_security_group.lb";
        "aws_alb.main"->"aws_subnet.public";
        "aws_cloudwatch_metric_alarm.service_cpu_high"->"aws_appautoscaling_policy.up";
        "aws_cloudwatch_metric_alarm.service_cpu_high"->"aws_ecs_cluster.main";
        "aws_cloudwatch_metric_alarm.service_cpu_high"->"aws_ecs_service.main";
        "aws_appautoscaling_target.target"->"aws_ecs_cluster.main";
        "aws_appautoscaling_target.target"->"aws_ecs_service.main";
        "aws_alb.main" [ shape=ellipse ];
        "aws_alb_listener.front_end" [ shape=ellipse ];
        "aws_alb_target_group.app" [ shape=ellipse ];
        "aws_appautoscaling_policy.down" [ shape=ellipse ];
        "aws_appautoscaling_policy.up" [ shape=ellipse ];
        "aws_appautoscaling_target.target" [ shape=ellipse ];
        "aws_cloudwatch_log_group.log_group" [ shape=ellipse ];
        "aws_cloudwatch_log_stream.log_stream" [ shape=ellipse ];
        "aws_cloudwatch_metric_alarm.service_cpu_high" [ shape=ellipse ];
        "aws_cloudwatch_metric_alarm.service_cpu_low" [ shape=ellipse ];
        "aws_ecr_lifecycle_policy.main" [ shape=ellipse ];
        "aws_ecr_repository.main" [ shape=ellipse ];
        "aws_ecs_cluster.main" [ shape=ellipse ];
        "aws_ecs_service.main" [ shape=ellipse ];
        "aws_ecs_task_definition.app" [ shape=ellipse ];
        "aws_eip.gw" [ shape=ellipse ];
        "aws_iam_policy.dynamodb" [ shape=ellipse ];
        "aws_iam_role.ecs_task_execution_role" [ shape=ellipse ];
        "aws_iam_role_policy_attachment.ecs_dynamodb_policy" [ shape=ellipse ];
        "aws_iam_role_policy_attachment.ecs_task_execution_role" [ shape=ellipse ];
        "aws_internet_gateway.gw" [ shape=ellipse ];
        "aws_nat_gateway.gw" [ shape=ellipse ];
        "aws_route.internet_access" [ shape=ellipse ];
        "aws_route_table.private" [ shape=ellipse ];
        "aws_route_table_association.private" [ shape=ellipse ];
        "aws_security_group.ecs_tasks" [ shape=rectangle ];
        "aws_security_group.lb" [ shape=rectangle ];
        "aws_subnet.private" [ shape=ellipse ];
        "aws_subnet.public" [ shape=ellipse ];
        "aws_vpc.main" [ shape=ellipse ];

}
```

**Comment by xescugc** [comment]
So with `--raw` it works ... 

Since this was opened I've checked the code several times and I cannot figure out in which case this is possible, the only way for me to fix this is to be able to reproduce it myself :(.

@luisdavim with just the output I cannot revert it to know how it happend. Would you be able to give me a version of your HCL that reproduces the error and has not sensible information? With that I would most likely be able to fix the issue :).

If not I'm still trying to figure it out but it looks impossible from the code but somehow it's done haha.

**Comment by xescugc** [comment]
The new version https://github.com/cycloidio/inframap/releases/tag/v0.6.4 has it solved :)
