### ISSUE TITLE
Brew install error

### ISSUE THREAD

**Issue by dq-peytz** [cycloidio/inframap#154]
![image](https://user-images.githubusercontent.com/84777812/129869199-3d5b4b5a-dd93-4e55-b769-bc8b54192f64.png)

**Comment by yermulnik** [comment]
Filed issue for `brew` too: https://github.com/Homebrew/brew/issues/11875

**Comment by yermulnik** [comment]
FYI: https://github.com/Homebrew/homebrew-core/issues/83571 had been fixed meaning this issue has been resolved.

**Comment by xlr-8** [comment]
> FYI: [Homebrew/homebrew-core#83571](https://github.com/Homebrew/homebrew-core/issues/83571) had been fixed meaning this issue has been resolved.

Can someone confirm the proper installation via Brew?

**Comment by yermulnik** [comment]
@xlr-8 Yep, I got it installed w/o issues on both of my Linux boxes:
```
> brew info inframap
inframap: stable 0.6.7 (bottled), HEAD
Read your tfstate or HCL to generate a graph
https://github.com/cycloidio/inframap
/home/linuxbrew/.linuxbrew/Cellar/inframap/0.6.7 (6 files, 18.4MB) *
  Poured from bottle on 2021-08-19 at 17:31:14
From: https://github.com/Homebrew/linuxbrew-core/blob/HEAD/Formula/inframap.rb
License: MIT
==> Dependencies
Build: go ✔
==> Options
--HEAD
        Install HEAD version
==> Analytics
install: 7 (30 days), 24 (90 days), 64 (365 days)
install-on-request: 7 (30 days), 23 (90 days), 63 (365 days)
build-error: 0 (30 days)
```

**Comment by xlr-8** [comment]
> @xlr-8 Yep, I got it installed w/o issues on both of my Linux boxes:

Cheers :+1: closing then
