### ISSUE TITLE
This project is not being kept current. Please update the readme.

### ISSUE THREAD

**Issue by volksdrvr** [cycloidio/inframap#226]
Please update either your readme to reflect the current state.

Leaving a project in the state without a warning in the documentation is not professional. I wasted a few hours so trust me when I say I will never waste yours.

This projects only purpose now is to drive you toward the company that has picked this one up.

**Comment by xescugc** [comment]
I try to do my best to keep it up to date, but I have 3 other OSS projects and my day to day work so at the end is a set of priorities that I have to manage.

If you have any request you can post it and I'll check it.
