### ISSUE TITLE
consider implementing a stdin source

### ISSUE THREAD

**Issue by BogdanSorlea** [cycloidio/inframap#228]
hey,

take scenario where one terraformer-generates tf files spread across folders and stuff, it would be great to have them visualised with inframap reading stdin or similar, so something like `cat generated/aws/*/*.tf | inframap generate | dot -Tpng > map.png` would be able to happen

**Comment by xescugc** [comment]
You can already use STDIN in Inframap, `cat state.tfstate | inframap generate` this is valid. OFC `cat generated/aws/*/*.tf ` is not valid as it's not possible, but you can do `inframap generate --hcl generate/aws/` and it'll read all the folder and if it's a module all the structure even if it has nested.

Could you try that?

**Comment by BogdanSorlea** [comment]
hey,
thanks for the input - only afterwards I noticed the `cat` in the man

however,
no luck - and I don't know why (might be a limitation of the way things are parsed(?), i.e. the tool can only generate the graph if the right kind of terraform HCL references are being used(?)):
```
(☸️ |aws-platform-production-eu-west-1:platform)➜  stag_network_diagram cat generated/aws/subnet/terraform.tfstate | inframap generate
strict digraph G {

}
(☸️ |aws-platform-production-eu-west-1:platform)➜  stag_network_diagram cat generated/aws/vpc/terraform.tfstate | inframap generate
strict digraph G {

}
(☸️ |aws-platform-production-eu-west-1:platform)➜  stag_network_diagram cat generated/aws/subnet/*.tf | inframap --hcl generate
strict digraph G {

}
(☸️ |aws-platform-production-eu-west-1:platform)➜  stag_network_diagram cat generated/aws/vpc/*.tf | inframap --hcl generate
strict digraph G {

}
(☸️ |aws-platform-production-eu-west-1:platform)➜  stag_network_diagram
```

**Comment by BogdanSorlea** [comment]
I'll close this one, as it answers my question and the rest is outside the scope
