### ISSUE TITLE
Document the internal flow of the software

### ISSUE THREAD

**Issue by skyzyx** [cycloidio/inframap#52]
Understanding how the internals of the software are organized, how logic is applied to data, and how code is grouped together would make it easier for interested people (like me) to make sense of the software and begin contributing fixes/features.

The `golangci-lint` project does a great job of this, and is what I have in mind. https://golangci-lint.run/contributing/architecture/

I saw a "how does it work?" section in the README, but it's a 30,000 foot view and I'm looking for a 1,000 foot view.

**Comment by xescugc** [comment]
Yep! The idea of the `How does it work` Is just the tip of the iceberg in terms that it only shows the general view of how it works. Then on the https://github.com/cycloidio/inframap/blob/master/CONTRIBUTING.md#add-a-new-provider we have a bit of info on how to add new Providers which explains a bit more about how do they work, so when you read the code it'll help.

But I agree we need a part of the documentation explaining the insides of the tool :).
